# Generated by Django 5.1.7 on 2025-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('veterinarian', 'Veterinarian'), ('receptionist', 'Receptionist'), ('pet_owner', 'Pet Owner')], default='pet_owner', max_length=100),
        ),
    ]
