# Generated by Django 5.1.7 on 2025-03-25 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_appointment_reminder_date_appointment_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('pet_owner', models.ForeignKey(limit_choices_to={'role': 'pet_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner_ratings', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(limit_choices_to={'role': 'veterinarian'}, on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
