# Generated by Django 5.1.7 on 2025-03-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_end_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
